# Generated by Django 5.2.6 on 2025-10-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone_no',
            field=models.CharField(max_length=11),
        ),
    ]
